 -- 실습: TOP-N QUERY 튜닝
 -- 01. 테스트용 테이블 생성
DROP TABLE TMP;
CREATE TABLE TMP (
COL1 NUMBER,
COL2 NUMBER,
COL3 NUMBER
);


INSERT INTO TMP
SELECT ROUND(DBMS_RANDOM.VALUE(1,10000), 0)
,ROUND(DBMS_RANDOM.VALUE(1,10000), 0)
,ROUND(DBMS_RANDOM.VALUE(1,10000), 0)
FROM DUAL
CONNECT BY LEVEL <= 1000000;

COMMIT;

CREATE INDEX TMP_IDX1 ON TMP(COL1, COL2);

SELECT * FROM TMP;

ALTER SESSION SET STATISTICS_LEVEL = 'ALL';

-- 02. TOP-N QUERY 만들기
SELECT * 
FROM (SELECT A.*, ROWNUM AS RONUM FROM (SELECT COL1, COL2, COL3
                                        FROM TMP
                                        WHERE COL1 >= 9789
                                        AND COL2  >= 5500
                                        ORDER BY COL1 desc, COL2) A)
WHERE ronum <=100;


-- 최적화 STEP 01
SELECT * FROM (
    SELECT V3.*, ROWNUM RN FROM (
        SELECT /*+ ORDERED USE_NL(V1 V2) */ V1.COL1, V1.COL2, V2.COL3 FROM (
            SELECT * FROM (
                SELECT /*+ LEADING INDEX_DESC(TMP TMP_IDX1) */ COL1, COL2, ROWNUM RN
                FROM TMP
                WHERE COL1 >= 9789
                AND COL2  >= 5500
                ORDER BY COL1 desc
            ) WHERE ROWNUM <= 100
            AND RN <= 100
        ) V1, TMP V2
        WHERE V1.COL1 = V2.COL1
        -- AND V1.COL2 = V2.COL2
        AND V1.COL2 >= 5500
        ORDER BY V2.COL1 DESC, V2.COL2
    ) V3 WHERE ROWNUM <= 200
    ORDER BY COL1 DESC, COL2
) WHERE RN BETWEEN 101 AND 200
;



DROP UNIQUE INDEX PK_DEPT;
select D.* from SCOTT.DEPT D
WHERE D.DEPTNO IN (
    SELECT E.DEPTNO FROM SCOTT.EMP E
);

SELECT D.* FROM (
    SELECT DEPTNO FROM SCOTT.EMP
) E, SCOTT.DEPT D 
WHERE D.DEPTNO IN (
    SELECT /*+ NO_UNNEST */ E.DEPTNO 
    FROM SCOTT.EMP E
);


SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR(NULL, NULL, 'ALLSTATS LAST'));

